#!/usr/bin/env python3
"""
WHAT'S NEW, AFTER EVERY SWITCH (#442; founder rule #459: no approval step).

Testers can't see progress unless we tell them. When a `switch` PR has merged, its "Testers' note:"
line goes to every onboarded client through the existing broadcast route (POST /api/dashboard/broadcast),
which honours opt-outs and the WhatsApp 24-hour window. The PR then gets a marker comment, so a note is
never sent twice.

Runs on a schedule, not on the merge event: a merge made by the watch's GITHUB_TOKEN starts no workflow.
Needs GitHub secrets APP_URL and COACH_DASHBOARD_KEY; without them it says so once and sends nothing.
"""
import json, os, sys, urllib.request, urllib.error
from datetime import datetime, timezone

REPO = os.environ["REPO"]
TOKEN = os.environ["GH_TOKEN"]
APP_URL = (os.environ.get("APP_URL") or "").rstrip("/")
KEY = os.environ.get("COACH_DASHBOARD_KEY") or ""
DRY = os.environ.get("DRY_RUN") == "1"
MARKER = "<!-- whats-new-sent -->"
# Ship as finished began with #459 (26 Sep, 11:29 UTC). Earlier switches were founder-only or already told.
SINCE = datetime(2026, 9, 26, 11, 29, tzinfo=timezone.utc)
FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
TAIL = "\n\nIf a reply from me looks wrong, just tell me. That's how I get better."


def gh(path, method="GET", body=None):
    req = urllib.request.Request(f"https://api.github.com/repos/{REPO}{path}", method=method,
                                 data=json.dumps(body).encode() if body is not None else None,
                                 headers={"Authorization": f"Bearer {TOKEN}", "Accept": "application/vnd.github+json"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read() or b"null")


def note_of(body):
    """The line that starts "Testers' note:", up to the next blank line. None if absent."""
    lines, out, on = (body or "").replace("\r", "").split("\n"), [], False
    for l in lines:
        if not on and l.strip().lower().startswith(("testers' note:", "testers’ note:")):
            on, l = True, l.split(":", 1)[1]
        elif on and not l.strip():
            break
        if on:
            out.append(l.strip())
    text = " ".join(x for x in out if x).strip()
    return text[:600] or None


def comment(pr, text):
    if DRY:
        print(f"DRY comment on #{pr}: {text}")
    else:
        gh(f"/issues/{pr}/comments", "POST", {"body": f"{MARKER}\n{text}{FOOTER}"})


def main():
    pulls = gh("/pulls?state=closed&sort=updated&direction=desc&per_page=30")
    for p in pulls:
        labels = {l["name"] for l in p.get("labels", [])}
        if not p.get("merged_at") or "switch" not in labels or "founder-only" in labels:
            continue
        if datetime.fromisoformat(p["merged_at"].replace("Z", "+00:00")) < SINCE:
            continue
        n = p["number"]
        if any(MARKER in (c.get("body") or "") for c in gh(f"/issues/{n}/comments?per_page=100")):
            continue
        note = note_of(p.get("body"))
        if not note:
            comment(n, "What's new: this switch PR has no `Testers' note:` line, so nothing was sent to testers.")
            continue
        if not APP_URL or not KEY:
            # Said once per PR via the marker; the founder action is in docs/SYSTEM.md.
            comment(n, "BLOCKED: the what's-new note was not sent. Add the GitHub secrets `APP_URL` and "
                       "`COACH_DASHBOARD_KEY` (the same values as in Railway), then delete this comment to resend.\n\n"
                       f"Note that would have gone out:\n> {note}")
            continue
        message = f"What's new at KamLife 🆕\n\n{note}{TAIL}"
        if DRY:
            print(f"DRY send for #{n}: {message!r}")
            continue
        req = urllib.request.Request(f"{APP_URL}/api/dashboard/broadcast", method="POST",
                                     data=json.dumps({"message": message, "filter": "all"}).encode(),
                                     headers={"Content-Type": "application/json", "x-dashboard-key": KEY})
        try:
            with urllib.request.urlopen(req, timeout=600) as r:
                res = json.loads(r.read() or b"{}")
            comment(n, f"What's new sent to testers: sent {res.get('sent')}, refused (opted out) {res.get('refused')}, "
                       f"substituted {res.get('substituted')}, failed {res.get('failed')} of {res.get('total')}.\n\n> {note}")
        except urllib.error.HTTPError as e:
            # No marker on a failed send: the next run tries again.
            print(f"#{n}: broadcast failed with HTTP {e.code}", file=sys.stderr)


if __name__ == "__main__":
    main()
